name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - uses: actions/checkout@v2
      - name: Caching Gatsby
        uses: actions/cache@v2
        with:
          path: |
            app/public
            app/.cache
            app/.firebase
            app/node_modules
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - run: cd app && npm i && npm run build
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          CI: true
      - uses: actions/setup-node@v3
        with:
          node-version: "22"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: app
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BELLEMONT }}'
          channelId: live
          projectId: bellemont
          target: ${{ fromJSON('["bellemont", "bellemont-full-site-dev"]')[github.ref != 'refs/heads/master'] }}
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
